/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { PerformanceReview } from "./PerformanceReview";
import { PerformanceReviewCountArgs } from "./PerformanceReviewCountArgs";
import { PerformanceReviewFindManyArgs } from "./PerformanceReviewFindManyArgs";
import { PerformanceReviewFindUniqueArgs } from "./PerformanceReviewFindUniqueArgs";
import { CreatePerformanceReviewArgs } from "./CreatePerformanceReviewArgs";
import { UpdatePerformanceReviewArgs } from "./UpdatePerformanceReviewArgs";
import { DeletePerformanceReviewArgs } from "./DeletePerformanceReviewArgs";
import { EmployeeProfile } from "../../employeeProfile/base/EmployeeProfile";
import { PerformanceReviewService } from "../performanceReview.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PerformanceReview)
export class PerformanceReviewResolverBase {
  constructor(
    protected readonly service: PerformanceReviewService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PerformanceReview",
    action: "read",
    possession: "any",
  })
  async _performanceReviewsMeta(
    @graphql.Args() args: PerformanceReviewCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PerformanceReview])
  @nestAccessControl.UseRoles({
    resource: "PerformanceReview",
    action: "read",
    possession: "any",
  })
  async performanceReviews(
    @graphql.Args() args: PerformanceReviewFindManyArgs
  ): Promise<PerformanceReview[]> {
    return this.service.performanceReviews(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PerformanceReview, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PerformanceReview",
    action: "read",
    possession: "own",
  })
  async performanceReview(
    @graphql.Args() args: PerformanceReviewFindUniqueArgs
  ): Promise<PerformanceReview | null> {
    const result = await this.service.performanceReview(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PerformanceReview)
  @nestAccessControl.UseRoles({
    resource: "PerformanceReview",
    action: "create",
    possession: "any",
  })
  async createPerformanceReview(
    @graphql.Args() args: CreatePerformanceReviewArgs
  ): Promise<PerformanceReview> {
    return await this.service.createPerformanceReview({
      ...args,
      data: {
        ...args.data,

        employeeProfile: args.data.employeeProfile
          ? {
              connect: args.data.employeeProfile,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PerformanceReview)
  @nestAccessControl.UseRoles({
    resource: "PerformanceReview",
    action: "update",
    possession: "any",
  })
  async updatePerformanceReview(
    @graphql.Args() args: UpdatePerformanceReviewArgs
  ): Promise<PerformanceReview | null> {
    try {
      return await this.service.updatePerformanceReview({
        ...args,
        data: {
          ...args.data,

          employeeProfile: args.data.employeeProfile
            ? {
                connect: args.data.employeeProfile,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PerformanceReview)
  @nestAccessControl.UseRoles({
    resource: "PerformanceReview",
    action: "delete",
    possession: "any",
  })
  async deletePerformanceReview(
    @graphql.Args() args: DeletePerformanceReviewArgs
  ): Promise<PerformanceReview | null> {
    try {
      return await this.service.deletePerformanceReview(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => EmployeeProfile, {
    nullable: true,
    name: "employeeProfile",
  })
  @nestAccessControl.UseRoles({
    resource: "EmployeeProfile",
    action: "read",
    possession: "any",
  })
  async getEmployeeProfile(
    @graphql.Parent() parent: PerformanceReview
  ): Promise<EmployeeProfile | null> {
    const result = await this.service.getEmployeeProfile(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
