/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EmployeeProfileWhereUniqueInput } from "../../employeeProfile/base/EmployeeProfileWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { EnumGoalStatus } from "./EnumGoalStatus";

@InputType()
class GoalWhereInput {
  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  deadline?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => EmployeeProfileWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EmployeeProfileWhereUniqueInput)
  @IsOptional()
  @Field(() => EmployeeProfileWhereUniqueInput, {
    nullable: true,
  })
  employeeProfile?: EmployeeProfileWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  milestone?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumGoalStatus,
  })
  @IsEnum(EnumGoalStatus)
  @IsOptional()
  @Field(() => EnumGoalStatus, {
    nullable: true,
  })
  status?: "Option1";
}

export { GoalWhereInput as GoalWhereInput };
