/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { FeedbackNoteUpdateManyWithoutEmployeeProfilesInput } from "./FeedbackNoteUpdateManyWithoutEmployeeProfilesInput";
import { Type } from "class-transformer";
import { GoalUpdateManyWithoutEmployeeProfilesInput } from "./GoalUpdateManyWithoutEmployeeProfilesInput";
import { KpiUpdateManyWithoutEmployeeProfilesInput } from "./KpiUpdateManyWithoutEmployeeProfilesInput";
import { NotificationUpdateManyWithoutEmployeeProfilesInput } from "./NotificationUpdateManyWithoutEmployeeProfilesInput";
import { PerformanceReviewUpdateManyWithoutEmployeeProfilesInput } from "./PerformanceReviewUpdateManyWithoutEmployeeProfilesInput";
import { ReportUpdateManyWithoutEmployeeProfilesInput } from "./ReportUpdateManyWithoutEmployeeProfilesInput";
import { ReviewTemplateUpdateManyWithoutEmployeeProfilesInput } from "./ReviewTemplateUpdateManyWithoutEmployeeProfilesInput";
import { TaskUpdateManyWithoutEmployeeProfilesInput } from "./TaskUpdateManyWithoutEmployeeProfilesInput";

@InputType()
class EmployeeProfileUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  department?: string | null;

  @ApiProperty({
    required: false,
    type: () => FeedbackNoteUpdateManyWithoutEmployeeProfilesInput,
  })
  @ValidateNested()
  @Type(() => FeedbackNoteUpdateManyWithoutEmployeeProfilesInput)
  @IsOptional()
  @Field(() => FeedbackNoteUpdateManyWithoutEmployeeProfilesInput, {
    nullable: true,
  })
  feedbackNotes?: FeedbackNoteUpdateManyWithoutEmployeeProfilesInput;

  @ApiProperty({
    required: false,
    type: () => GoalUpdateManyWithoutEmployeeProfilesInput,
  })
  @ValidateNested()
  @Type(() => GoalUpdateManyWithoutEmployeeProfilesInput)
  @IsOptional()
  @Field(() => GoalUpdateManyWithoutEmployeeProfilesInput, {
    nullable: true,
  })
  goals?: GoalUpdateManyWithoutEmployeeProfilesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  jobRole?: string | null;

  @ApiProperty({
    required: false,
    type: () => KpiUpdateManyWithoutEmployeeProfilesInput,
  })
  @ValidateNested()
  @Type(() => KpiUpdateManyWithoutEmployeeProfilesInput)
  @IsOptional()
  @Field(() => KpiUpdateManyWithoutEmployeeProfilesInput, {
    nullable: true,
  })
  kpis?: KpiUpdateManyWithoutEmployeeProfilesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => NotificationUpdateManyWithoutEmployeeProfilesInput,
  })
  @ValidateNested()
  @Type(() => NotificationUpdateManyWithoutEmployeeProfilesInput)
  @IsOptional()
  @Field(() => NotificationUpdateManyWithoutEmployeeProfilesInput, {
    nullable: true,
  })
  notifications?: NotificationUpdateManyWithoutEmployeeProfilesInput;

  @ApiProperty({
    required: false,
    type: () => PerformanceReviewUpdateManyWithoutEmployeeProfilesInput,
  })
  @ValidateNested()
  @Type(() => PerformanceReviewUpdateManyWithoutEmployeeProfilesInput)
  @IsOptional()
  @Field(() => PerformanceReviewUpdateManyWithoutEmployeeProfilesInput, {
    nullable: true,
  })
  performanceReviews?: PerformanceReviewUpdateManyWithoutEmployeeProfilesInput;

  @ApiProperty({
    required: false,
    type: () => ReportUpdateManyWithoutEmployeeProfilesInput,
  })
  @ValidateNested()
  @Type(() => ReportUpdateManyWithoutEmployeeProfilesInput)
  @IsOptional()
  @Field(() => ReportUpdateManyWithoutEmployeeProfilesInput, {
    nullable: true,
  })
  reports?: ReportUpdateManyWithoutEmployeeProfilesInput;

  @ApiProperty({
    required: false,
    type: () => ReviewTemplateUpdateManyWithoutEmployeeProfilesInput,
  })
  @ValidateNested()
  @Type(() => ReviewTemplateUpdateManyWithoutEmployeeProfilesInput)
  @IsOptional()
  @Field(() => ReviewTemplateUpdateManyWithoutEmployeeProfilesInput, {
    nullable: true,
  })
  reviewTemplates?: ReviewTemplateUpdateManyWithoutEmployeeProfilesInput;

  @ApiProperty({
    required: false,
    type: () => TaskUpdateManyWithoutEmployeeProfilesInput,
  })
  @ValidateNested()
  @Type(() => TaskUpdateManyWithoutEmployeeProfilesInput)
  @IsOptional()
  @Field(() => TaskUpdateManyWithoutEmployeeProfilesInput, {
    nullable: true,
  })
  tasks?: TaskUpdateManyWithoutEmployeeProfilesInput;
}

export { EmployeeProfileUpdateInput as EmployeeProfileUpdateInput };
