/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { FeedbackNoteListRelationFilter } from "../../feedbackNote/base/FeedbackNoteListRelationFilter";
import { GoalListRelationFilter } from "../../goal/base/GoalListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { KpiListRelationFilter } from "../../kpi/base/KpiListRelationFilter";
import { NotificationListRelationFilter } from "../../notification/base/NotificationListRelationFilter";
import { PerformanceReviewListRelationFilter } from "../../performanceReview/base/PerformanceReviewListRelationFilter";
import { ReportListRelationFilter } from "../../report/base/ReportListRelationFilter";
import { ReviewTemplateListRelationFilter } from "../../reviewTemplate/base/ReviewTemplateListRelationFilter";
import { TaskListRelationFilter } from "../../task/base/TaskListRelationFilter";

@InputType()
class EmployeeProfileWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  department?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => FeedbackNoteListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FeedbackNoteListRelationFilter)
  @IsOptional()
  @Field(() => FeedbackNoteListRelationFilter, {
    nullable: true,
  })
  feedbackNotes?: FeedbackNoteListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => GoalListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GoalListRelationFilter)
  @IsOptional()
  @Field(() => GoalListRelationFilter, {
    nullable: true,
  })
  goals?: GoalListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  jobRole?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => KpiListRelationFilter,
  })
  @ValidateNested()
  @Type(() => KpiListRelationFilter)
  @IsOptional()
  @Field(() => KpiListRelationFilter, {
    nullable: true,
  })
  kpis?: KpiListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => NotificationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => NotificationListRelationFilter)
  @IsOptional()
  @Field(() => NotificationListRelationFilter, {
    nullable: true,
  })
  notifications?: NotificationListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PerformanceReviewListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PerformanceReviewListRelationFilter)
  @IsOptional()
  @Field(() => PerformanceReviewListRelationFilter, {
    nullable: true,
  })
  performanceReviews?: PerformanceReviewListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ReportListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ReportListRelationFilter)
  @IsOptional()
  @Field(() => ReportListRelationFilter, {
    nullable: true,
  })
  reports?: ReportListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ReviewTemplateListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ReviewTemplateListRelationFilter)
  @IsOptional()
  @Field(() => ReviewTemplateListRelationFilter, {
    nullable: true,
  })
  reviewTemplates?: ReviewTemplateListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TaskListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TaskListRelationFilter)
  @IsOptional()
  @Field(() => TaskListRelationFilter, {
    nullable: true,
  })
  tasks?: TaskListRelationFilter;
}

export { EmployeeProfileWhereInput as EmployeeProfileWhereInput };
