/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ReviewTemplateService } from "../reviewTemplate.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReviewTemplateCreateInput } from "./ReviewTemplateCreateInput";
import { ReviewTemplate } from "./ReviewTemplate";
import { ReviewTemplateFindManyArgs } from "./ReviewTemplateFindManyArgs";
import { ReviewTemplateWhereUniqueInput } from "./ReviewTemplateWhereUniqueInput";
import { ReviewTemplateUpdateInput } from "./ReviewTemplateUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReviewTemplateControllerBase {
  constructor(
    protected readonly service: ReviewTemplateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ReviewTemplate })
  @nestAccessControl.UseRoles({
    resource: "ReviewTemplate",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createReviewTemplate(
    @common.Body() data: ReviewTemplateCreateInput
  ): Promise<ReviewTemplate> {
    return await this.service.createReviewTemplate({
      data: {
        ...data,

        employeeProfile: data.employeeProfile
          ? {
              connect: data.employeeProfile,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        department: true,

        employeeProfile: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        role: true,
        templateContent: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ReviewTemplate] })
  @ApiNestedQuery(ReviewTemplateFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ReviewTemplate",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reviewTemplates(
    @common.Req() request: Request
  ): Promise<ReviewTemplate[]> {
    const args = plainToClass(ReviewTemplateFindManyArgs, request.query);
    return this.service.reviewTemplates({
      ...args,
      select: {
        createdAt: true,
        department: true,

        employeeProfile: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        role: true,
        templateContent: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ReviewTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReviewTemplate",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reviewTemplate(
    @common.Param() params: ReviewTemplateWhereUniqueInput
  ): Promise<ReviewTemplate | null> {
    const result = await this.service.reviewTemplate({
      where: params,
      select: {
        createdAt: true,
        department: true,

        employeeProfile: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        role: true,
        templateContent: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ReviewTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReviewTemplate",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateReviewTemplate(
    @common.Param() params: ReviewTemplateWhereUniqueInput,
    @common.Body() data: ReviewTemplateUpdateInput
  ): Promise<ReviewTemplate | null> {
    try {
      return await this.service.updateReviewTemplate({
        where: params,
        data: {
          ...data,

          employeeProfile: data.employeeProfile
            ? {
                connect: data.employeeProfile,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          department: true,

          employeeProfile: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,
          role: true,
          templateContent: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ReviewTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReviewTemplate",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReviewTemplate(
    @common.Param() params: ReviewTemplateWhereUniqueInput
  ): Promise<ReviewTemplate | null> {
    try {
      return await this.service.deleteReviewTemplate({
        where: params,
        select: {
          createdAt: true,
          department: true,

          employeeProfile: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,
          role: true,
          templateContent: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
